# Use Node.js 8
language: node_js
node_js:
  - 8

# Require docker servie for building images during tests
services:
  docker

# Do linting, coverage, and build docs (to upload to Github pages)
script:
  - make lint
  - make cover
  - make docs

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy a new version of NPM package and create a Github release
  - provider: script
    skip_cleanup: true
    script:
      - npm run semantic-release

  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
