# Use Node.js 8 and cache packages
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules

# Require docker servie for building images during tests
services:
  docker

# Do linting, coverage, and build docs (to upload to github pages)
script:
  - make lint
  - make cover
  - make build
  - make docs

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Rename (remove OS suffixes) and zip binary builds
before_deploy:
  - tar --transform "s|build/dockter-linux|dockter|" -czvf build/dockter-linux-x64.tar.gz build/dockter-linux
  - tar --transform "s|build/dockter-macos|dockter|" -czvf build/dockter-macos-x64.tar.gz build/dockter-macos
  - mv build/dockter-win.exe build/dockter.exe ; zip -j build/dockter-win-x64.zip build/dockter.exe

deploy:
  # Deploy a new version of NPM package and create a Github release
  - provider: script
    skip_cleanup: true
    script:
      - npm run semantic-release

  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
