# Use Node.js
language: node_js
node_js:
  - '10'
  - '12'

# Require docker service for building images during tests
services:
  docker

# Do linting, coverage, etc and build docs (to upload to Github pages)
script:
  - make lint
  - make cover
  - make build
  - make docs

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Prevent Github Pages from using Jekyll
# which causes docs files starting with underscores to be ignored
before_deploy:
  - touch docs/.nojekyll

deploy:
  # Deploy a new version of NPM package and create a Github release
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_NODE_VERSION = '12'

  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_NODE_VERSION = '12'
